### ISSUE TITLE
按照文档使用docker-compose方式部署提示短链接不存在或已过期

### ISSUE THREAD

**Issue by PIUIFU** [CareyWang/MyUrls#12]
如题，两台服务器均出现如上错误，想用来单纯做短链工具，并未与sub-web项目配合使用，请大佬指点一下

**Comment by CareyWang** [comment]
@PIUIFU 可以拉取下最新代码再尝试下，修复了一个问题。通过 curl 验证服务状况：
curl --location --request POST 'http://YOUR_IP:8002/short' --form 'longUrl="aHR0cHM6Ly93d3cuYmFpZHUuY29t"'

**Comment by PIUIFU** [comment]
已解决，非常感谢！
