### ISSUE TITLE
使用Railway一键部署出错 

### ISSUE THREAD

**Issue by rookiecloud** [CareyWang/MyUrls#16]
Deploy logs:
standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by cgkings** [comment]
同样的问题，按照作者的说明一步步走，不管手动、docker、railway一键部署全部失败，是不是有操作作者的教程没有说明？

**Comment by CareyWang** [comment]
railway 等第三方平台部署不做保证，docker-compose 部署失败可以 `docker-compose logs -f` 查看日志定位。

**Comment by pzcn** [comment]
> Deploy logs: standard_init_linux.go:219: exec user process caused: no such file or directory



> 同样的问题，按照作者的说明一步步走，不管手动、docker、railway一键部署全部失败，是不是有操作作者的教程没有说明？

已修复 重新部署即可
