### ISSUE TITLE
特别长的链接转换的短链打开后是404

### ISSUE THREAD

**Issue by superabbite1** [CareyWang/MyUrls#18]
发现一些特别长的链接转换成的短链无法打开提示404，这个是什么原因

**Comment by wxyShine** [comment]
[试试这个](https://github.com/wxyShine/short-url)

**Comment by 281677160** [comment]
> [试试这个](https://github.com/wxyShine/short-url)

这个比CareyWang大佬的安装更云里雾里的，CareyWang大佬的谷歌或者百度还能找到比较有用的方法，你说这个我刚测试了一下，完全不懂
看说明是下载short-url.jar，然后执行java -jar -Xms128m -Xmx512m -XX:PermSize=128M -XX:MaxPermSize=256M  short-url.jar
然后是没然后了，等半天都不知道运行完了没，一直卡一个地方不动了

**Comment by CareyWang** [comment]
理论上404属于没有转换成功。可换其他现有服务重试是否复现，或提供具体链接

**Comment by bfmen** [comment]
确实会这样 无法打开 特别长的链接
