### ISSUE TITLE
大佬 能不能看下 sub-web 短链接获取失败

### ISSUE THREAD

**Issue by cs-star** [CareyWang/MyUrls#20]
https://sub.aa01.ml  https://zz01.ml  对接怎么不能 短链接获取 不知道哪里设置了

**Comment by CareyWang** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/33325726/161910534-ca8203cc-cc0c-48cb-84b5-8b840d4dc172.png">
测试无问题

**Comment by cs-star** [comment]
谢谢大佬 秒回  在sub web 页面 打不开

**Comment by CareyWang** [comment]
@cs-star Access to XMLHttpRequest at 'https://zz01.ml/short' from origin 'https://sub.aa01.ml' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

反代未正确配置跨域

**Comment by cs-star** [comment]
#PROXY-START/
location /
{
    proxy_pass http://zz01.ml:8001;
    proxy_set_header Host zz01.ml;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header 'Access-Control-Allow-Origin' '*';
}

#PROXY-END/

太感谢了
