### ISSUE TITLE
如何将MyUrls接入sub-web

### ISSUE THREAD

**Issue by Wyatt323** [CareyWang/MyUrls#24]
我已经在.vue文件里添加了 我的域名/short 但是在前端调用的时候，还是会显示短链接获取失败，短链接单独使用是没问题的

**Comment by CareyWang** [comment]
需要配置反向代理，添加跨域响应 `header Access-Control-Allow-Origin: *`

**Comment by Wyatt323** [comment]
现在出现了新的问题，subweb可以获取成功短连接了，但是获取出来的短链接访问是显示 短链接不存在或已过期
这个该如何解决

**Comment by zeusngng** [comment]
> 现在出现了新的问题，subweb可以获取成功短连接了，但是获取出来的短链接访问是显示 短链接不存在或已过期 这个该如何解决

你好，我遇到了相同的问题，安装Redis 服务后一切正常工作。

**Comment by TaoRone** [comment]
同遇到此问题
