### ISSUE TITLE
arm64的机子该如何采用docker的方式运行呢？

### ISSUE THREAD

**Issue by ypxun** [CareyWang/MyUrls#25]
改了`.env`和`backend`，docker compose跑了下，报错和 #21 一样，`exec format error`。能给指下解决方向不，具体实现步骤我可以查，真搞不明白再问。

**Comment by CareyWang** [comment]
暂时可修改 [Dockerfile](https://github.com/CareyWang/MyUrls/blob/cb43a278488f4d575783c878e92e3e493d2ecb75/Dockerfile#L11) 中 amd64 为 arm64 解决

**Comment by ypxun** [comment]
> 暂时可修改 [Dockerfile](https://github.com/CareyWang/MyUrls/blob/cb43a278488f4d575783c878e92e3e493d2ecb75/Dockerfile#L11) 中 amd64 为 arm64 解决

arm64的包通过Actions搞了下，有了。不过我看才3M大小，对吗（看到有报错）？docker方式安装的话是不是没必要用了？
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/20849726/202911319-23bf9e09-0b43-4490-9982-e25805ea66c3.png">

**Comment by CareyWang** [comment]
@ypxun 有自建redis的话，可以直接使用action编译产出

**Comment by ypxun** [comment]
> @ypxun 有自建redis的话，可以直接使用action编译产出

现在是碰到了 #7 同样的问题，短点的链接缩短没问题，太长的链接缩短后的短链打开直接502。我也尝试了他的解决方法，把
```
client_max_body_size 100M;
client_body_buffer_size 1M;
client_header_buffer_size 5120k;
large_client_header_buffers 16 5120k;
```放在了nginx的`http`区块里，短链接的页面还是502，请问还应该排查哪里呢？

**Comment by ypxun** [comment]
@CareyWang  可以指导下吗？我看了容器的日志，没有异常。可是太长的链接转换出来的短链接依然502，不知道还应该从哪里排错。
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20849726/203472722-3fb7cc1a-8b56-472b-929d-ff5b40e5a8da.png">

**Comment by CareyWang** [comment]
@ypxun 提供原异常链接

**Comment by ypxun** [comment]
> @ypxun 提供原异常链接

抱歉，刚才有点事耽搁了。
处理了下数据，短链接：`https://myurls.opk.app/lQuV8jF`
长链接：`https://subc.opk.app/sub?target=clash&url=vmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czEiLA0KICAiYWRkIjogIjEyMy5jb20iLA0KICAicG9ydCI6ICI0NDMiLA0KICAiaWQiOiAiYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgInRscyI6ICJ0bHMiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czIiLA0KICAiYWRkIjogIjQ1Ni5jb20iLA0KICAicG9ydCI6ICI0NDMiLA0KICAiaWQiOiAiYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgInRscyI6ICJ0bHMiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czMiLA0KICAiYWRkIjogIjc4OS5jb20iLA0KICAicG9ydCI6ICI0NDMiLA0KICAiaWQiOiAiYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgInRscyI6ICJ0bHMiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czQiLA0KICAiYWRkIjogIjEuY29tIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImIwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiL2IwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czUiLA0KICAiYWRkIjogIjIuY29tIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImIwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiL2IwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czYiLA0KICAiYWRkIjogIjMuY29tIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImIwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiL2IwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czciLA0KICAiYWRkIjogIjExMjMuY29tIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImIwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiL2IwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czgiLA0KICAiYWRkIjogIjIxMi5jb20iLA0KICAicG9ydCI6ICI0NDMiLA0KICAiaWQiOiAiYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvYjBjOTVjMzgtN2MzOS00ZTVhLTllNTYtNjRiZTliYWNiMGYwIiwNCiAgInRscyI6ICJ0bHMiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImRpcmVjdF9kb191czkiLA0KICAiYWRkIjogIjM1NjcuY29tIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImIwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiL2IwYzk1YzM4LTdjMzktNGU1YS05ZTU2LTY0YmU5YmFjYjBmMCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7C&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2Fypxun%2Fmagic%2Fmaster%2Frules.ini&emoji=true&list=false&tfo=false&scv=true&fdn=false&sort=false&new_name=true`

**Comment by ypxun** [comment]
@CareyWang 大佬，你那测试有问题没？我今天试了下别人的后端和前端。也是有的可以，有的不行。

**Comment by CareyWang** [comment]
该问题由反向代理层引入，不通过反向代理直接请求服务无问题。
可 Google `upstream sent too big header while reading response header from upstream` 解决

**Comment by ypxun** [comment]
> 该问题由反向代理层引入，不通过反向代理直接请求服务无问题。 可 Google `upstream sent too big header while reading response header from upstream` 解决

谢谢大佬，大佬nb。谷歌抄来的代码放在nginx里解决了：
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
proxy_busy_buffers_size 512k;
proxy_buffers 4 512k;
proxy_buffer_size 256k;
```
