### ISSUE TITLE
搭建完成后，可以通过https访问前端页面，但是将长连接进行转换后，出现的是http的链接

### ISSUE THREAD

**Issue by Wyatt323** [CareyWang/MyUrls#26]
![image](https://user-images.githubusercontent.com/71224625/202913535-c9e48928-3428-4464-b7e2-6191175005a1.png)

**Comment by ypxun** [comment]
确定pulic/index.html没写错吗？

**Comment by Wyatt323** [comment]
没写错，index.html里面写的https://我的域名
