### ISSUE TITLE
构建docker编译出错

### ISSUE THREAD

**Issue by ruinny** [CareyWang/MyUrls#27]
修改index.html之后，重新构建镜像出错，应该是go编译的时候有问题

Status: Downloaded newer image for golang:1.19-alpine
 ---> feb4bbda921c
Step 2/15 : WORKDIR /app
 ---> Running in 66c72d90d14b
Removing intermediate container 66c72d90d14b
 ---> e8edd07e9474
Step 3/15 : RUN go env -w GO111MODULE="on" && go env -w GOPROXY="https://goproxy.cn,direct"
 ---> Running in 245e10d4448c
Removing intermediate container 245e10d4448c
 ---> 0cc71ab9e924
Step 4/15 : COPY go.sum go.mod ./
 ---> 91c8cb9c3f17
Step 5/15 : RUN go mod tidy
 ---> Running in 3d6300222a0c
go: warning: "all" matched no packages
Removing intermediate container 3d6300222a0c
 ---> 60d212c5c04d
Step 6/15 : FROM dependencies as build
 ---> 60d212c5c04d
Step 7/15 : WORKDIR /app
 ---> Running in 8e5ec242fef2
Removing intermediate container 8e5ec242fef2
 ---> 401364df6317
Step 8/15 : COPY main.go ./
 ---> 64424ec478b5
Step 9/15 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o myurls main.go
 ---> Running in 197b4d1483b0
main.go:14:2: no required module provides package github.com/gin-gonic/gin; to add it:
        go get github.com/gin-gonic/gin
main.go:15:2: no required module provides package github.com/gomodule/redigo/redis; to add it:
        go get github.com/gomodule/redigo/redis
main.go:16:2: no required module provides package github.com/sirupsen/logrus; to add it:
        go get github.com/sirupsen/logrus
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o myurls main.go' returned a non-zero code: 1

到这里就出错了，大佬帮忙看看。docker-compose 一样的问题

debain11

**Comment by CareyWang** [comment]
fixed
