### ISSUE TITLE
求自定义短链接后缀长度的方法？

### ISSUE THREAD

**Issue by vitaminx** [CareyWang/MyUrls#29]
个人小范围使用的 MyUrls 不需要很长的后缀，四位乃至三位长度就够了，七位实在用不上，请问需要这么修改或者有变量参数设置吗？

**Comment by CareyWang** [comment]
@vitaminx https://github.com/CareyWang/MyUrls/blob/dbbb315d1feef47f329c78916fae70941413141d/main.go#L187

**Comment by vitaminx** [comment]
谢谢！

**Comment by vitaminx** [comment]
> @vitaminx
> 
> https://github.com/CareyWang/MyUrls/blob/dbbb315d1feef47f329c78916fae70941413141d/main.go#L187

对了，我一直都用你编译好的文件😭，请问能不能在 index.html 里面留一个接口？

**Comment by vitaminx** [comment]
感谢已实现短链接后缀 3 位长度👇

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/myurls-3.png)

但是 sub-web-modify 短链接后缀长度还是 7 位长度，是不是 api 也需要修改，请问怎么才能实现？

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/sub-3.png)
