### ISSUE TITLE
请问使用docker部署如何更改前端页面中http://example.com/

### ISSUE THREAD

**Issue by ainuoyan** [CareyWang/MyUrls#3]
请问使用docker部署如何更改前端页面中http://example.com/

**Comment by ainuoyan** [comment]
.env 中已经更改 MYURLS_DOMAIN 为我的域名，但是使用的时候前端页面还是默认的，我不知道改怎么修改

**Comment by ainuoyan** [comment]
目前使用nginx文本替换暂时解决了，请问还有其他好办法吗？

**Comment by CareyWang** [comment]
@ainuoyan clone项目到本地，修改 public/index.html，执行 docker build 构建本地镜像运行。

**Comment by ainuoyan** [comment]
> @ainuoyan clone项目到本地，修改 public/index.html，执行 docker build 构建本地镜像运行。

好的，谢谢，

**Comment by szsyzx** [comment]
clone项目到本地，修改 public/index.html，执行 docker build 构建本地镜像运行。

执行 docker build 构建本地镜像运行。

具体需要怎么做
