### ISSUE TITLE
已实现后缀长度 3 位，但 API 获取还是 7 位，请问如何修改？

### ISSUE THREAD

**Issue by vitaminx** [CareyWang/MyUrls#30]
感谢已实现短链接后缀 3 位长度👇

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/myurls-3.png)

但是 sub-web-modify 短链接后缀长度还是 7 位长度，是不是 api 也需要修改，请问怎么才能实现？

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/sub-3.png)

**Comment by vitaminx** [comment]
搞定了

**Comment by Atomic994** [comment]
> 搞定了

请问怎么解决的？可以分享一下吗
