### ISSUE TITLE
Easier Installation

### ISSUE THREAD

**Issue by iamtheted** [CareyWang/MyUrls#34]
Hello there!
I hope you're doing great! 

I was wondering if you could provide an easier installation, so that everyone could have this link shortner.
As of now, it's too complicated to be honest.

Please let me know,
Thanks a lot!

**Comment by iamtheted** [comment]
Also isn't there any way to apply SSL by LetsEncrypt using UVICORN?

**Comment by CareyWang** [comment]
You can clone repo and rename `.env.example` to `.env`. Modify the variables in the `.env` file according to the actual situation, then run `docker-compose up -d`. The service will start normally and listen on the port you have configured. 

Installation and usage of Docker and docker-compose, please refer to the [official documentation](https://docs.docker.com/compose/install/).

SSL is not supported in this project, you can use a reverse proxy like nginx or caddy to solve it, or use Cloudflare CDN.
