### ISSUE TITLE
已经配置了正确的跨域，浏览器F12看还是报错

### ISSUE THREAD

**Issue by Faramitas** [CareyWang/MyUrls#37]
@cs-star Access to XMLHttpRequest at 'https://zz01.ml/short' from origin 'https://sub.aa01.ml' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

反代未正确配置跨域

_Originally posted by @CareyWang in https://github.com/CareyWang/MyUrls/issues/20#issuecomment-1089879672_
            
![65e08baaf376318d4c9a989dea010500](https://user-images.githubusercontent.com/29322214/270361914-be32330d-025b-4f80-a940-a5b1babd2d0b.png)
![1695649276533](https://user-images.githubusercontent.com/29322214/270361956-7dd7c7d9-46c1-423d-b9b4-ac1644272caf.jpg)
![](https://al.faramita.xyz:444/d/%E5%A4%B8%E5%85%8B%E7%BD%91%E7%9B%98/d81dd424d63913a1c431329eab629d56.png)
![](https://al.faramita.xyz:444/d/%E5%A4%B8%E5%85%8B%E7%BD%91%E7%9B%98/782ce798f719b4f8608a9e95e1fcb0d8.png)

*********************************************************************
**找到原因了，sub-web短链接API后面一定要加上/short！！！！**

**Comment by Faramitas** [comment]
我测试了一下，浏览器安装了CORS的插件，还是会报错

**Comment by Faramitas** [comment]
我把sub-web的短链接API换成https://suo.yt/也不行
![image](https://github.com/CareyWang/MyUrls/assets/29322214/287fa33e-656a-49ef-a250-2ef61a00da27)

**Comment by bfmen** [comment]
这个解决了跨域问题  sub-web短链接API后面一定要加上/short

**Comment by 518512** [comment]
> /short

能否麻烦截图看一下，我NPM 设置后 还是不行
