### ISSUE TITLE
大佬，新版本后，前端的页面部署了打不开

### ISSUE THREAD

**Issue by TaoRone** [CareyWang/MyUrls#42]
和之前版本一样反代，，权限、内存空间都没问题，但还是直接返回502
服务器内curl也是502
部署方式docker-compose 
这次没有修改index.html，也没有修改docker-compose 
仅仅修改了env文件

MYURLS_PORT=9002
MYURLS_DOMAIN=s2.sky11111.com
MYURLS_PROTO=https

求救啊……

**Comment by org100** [comment]
貌似不能改端口，改了就无法打开

**Comment by TaoRone** [comment]
> 貌似不能改端口，改了就无法打开

确实，好离谱……

**Comment by TaoRone** [comment]
大佬，更新的时候再加入一个如何利用已存在的redis方式吧……
我进行了类似这样的修改，但是依然不能用

 entrypoint: ["/app/myurls", "-domain", "${MYURLS_DOMAIN}", "-conn", "${MYURLS_REDIS_CONN}", "-password", "${MYURLS_REDIS_PASSWORD}"]

MYURLS_PORT=9002
MYURLS_DOMAIN=s2.sky11111.com
MYURLS_PROTO=https
MYURLS_REDIS_CONN=redis-nl5.sky.ceo:16379
MYURLS_REDIS_PASSWORD=Z*Fe9x*5U7y

**Comment by CareyWang** [comment]
@TaoRone 使用独立部署的redis，建议直接 docker run 运行即可，参考 readme

**Comment by CareyWang** [comment]
端口问题已修复
