### ISSUE TITLE
大佬，那个logo，可以不是换成本地路径？因为那个cdn好像国内访问好慢

### ISSUE THREAD

**Issue by yu1ec** [CareyWang/MyUrls#44]
https://cdn.jsdelivr.net/gh/CareyWang/MyUrls@master/public/logo.png

**Comment by CareyWang** [comment]
[fixed](https://github.com/CareyWang/MyUrls/commit/b7dd2bbfa882ab561ea0cc8d33f0d31a94c1afc8)
