### ISSUE TITLE
希望增加ARM64支持

### ISSUE THREAD

**Issue by MFYDev** [CareyWang/MyUrls#5]
Carey您好~

最近我购买了树莓派4B，然后在考虑把公网服务器的服务迁移到树莓派上，这个短链服务我一直觉得很喜欢所以也想迁移过来，但是并没有ARM64的支持，所以想问一下有任何支持ARM64的计划吗？

**Comment by CareyWang** [comment]
@MFYDev 如果可以，建议使用 docker-compose 部署，仓库已提供 docker-compose.yml 。

项目编译ARM平台可执行文件没有问题，如果需要的话可以帮忙编译一份，但是服务用到了redis，可能需要自行解决缓存数据库的安装问题。

**Comment by MFYDev** [comment]
@CareyWang    Carey晚上好~不好意思刚到家，立刻编译了arm64的二进制文件并且完善了README，已经创建PR #6
