### ISSUE TITLE
出现无法访问短网址

### ISSUE THREAD

**Issue by JarmoHu** [CareyWang/MyUrls#7]
一开始是打开https://suo.yt，可以访问首页，但是打不开短网址
我又自己建了一个，关掉CDN也是一样的

**Comment by CareyWang** [comment]
@JarmoHu 检查本地网络到Cloudflare连通情况，目前线上无问题。自建无法访问，提供请求方式以及详细报错信息。

**Comment by JarmoHu** [comment]
不好意思，我发现不是好像可以用，但是只要是我的源链接太长就会出现该情况怎么办？

**Comment by CareyWang** [comment]
@JarmoHu 具体原因请 Google “GET请求 URL长度限制”

**Comment by JarmoHu** [comment]
感谢您的帮助，我这里贴一下我搜索后的解决方式：
在nginx设置中的`server`里添加如下几行
```nginx
    client_max_body_size 24M;
    client_body_buffer_size 128k;

    client_header_buffer_size 5120k;
    large_client_header_buffers 16 5120k;
```

**Comment by szsyzx** [comment]
@JarmoHu 兄弟你是如何用nginx部署的能否教下
