### ISSUE TITLE
太难装了，按照教程折腾了一天也没搞定

### ISSUE THREAD

**Issue by szsyzx** [CareyWang/MyUrls#8]
太难装了，按照教程折腾了一天也没搞定

老大能不能出个小白教程啊

**Comment by CareyWang** [comment]
建议使用 docker，参考 https://github.com/CareyWang/MyUrls#docker

**Comment by szsyzx** [comment]
感谢老大的回复 对小白的我来说太难了，最好有个傻瓜教程！

**Comment by szsyzx** [comment]
@CareyWang 老大可否出个小白教程

**Comment by szsyzx** [comment]
老大是不是这样的

Docker



方法一：docker run -d --restart always --name myurls careywong/myurls:latest -domain example.com -port 8002 -conn 127.0.0.1:6379 -passwd '' -ttl 90方法二：git clone https://github.com/CareyWang/MyUrls.git MyUrls cd MyUrls cp .env.example .env docker-compose up -d




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 晚上10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CareyWang/MyUrls] 太难装了，按照教程折腾了一天也没搞定 (#8)





 
建议使用 docker，参考 https://github.com/CareyWang/MyUrls#docker

**Comment by szsyzx** [comment]
老大有木有小白教程给个地址啊

**Comment by CareyWang** [comment]
> 老大是不是这样的 Docker 方法一：docker run -d --restart always --name myurls careywong/myurls:latest -domain example.com -port 8002 -conn 127.0.0.1:6379 -passwd '' -ttl 90方法二：git clone https://github.com/CareyWang/MyUrls.git MyUrls cd MyUrls cp .env.example .env docker-compose up -d
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月31日(星期三) 晚上10:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [CareyWang/MyUrls] 太难装了，按照教程折腾了一天也没搞定 (#8) 建议使用 docker，参考 https://github.com/CareyWang/MyUrls#docker — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CareyWang** [comment]
Docker 直接运行，需要自己搭建 redis。使用 docker-compose 的话，只需要按步骤修改 .env 中对应参数即可。

**Comment by cgkings** [comment]
> Docker 直接运行，需要自己搭建 redis。使用 docker-compose 的话，只需要按步骤修改 .env 中对应参数即可。
1、git clone https://github.com/CareyWang/MyUrls.git MyUrls
2、cd MyUrls
3、cp .env.example .env
4、编辑/home/MyUrls/.env和/home/MyUrls/public/index.html
5、docker-compose up -d
6、访问自己.env编辑的域名，访问失败：
该网页无法正常运作x-go.gq 目前无法处理此请求。
HTTP ERROR 502

**Comment by cgkings** [comment]
> docker-compose logs -f
感谢你的回复，运行docker-compose logs -f显示内容如下：
![image](https://user-images.githubusercontent.com/58586625/148147407-09ec89fd-1201-4541-95c7-791e47dd5761.png)
访问我设置的域名，显示如下：
![image](https://user-images.githubusercontent.com/58586625/148147467-ee0cec51-6d34-4d10-9de2-fd6aea2139a7.png)

**Comment by CareyWang** [comment]
@cgkings 服务启动应该没有问题，检查下caddy反代配置是否正确。本地可通过 curl http://127.0.0.1:{port}/aaa 测试服务是否正常

**Comment by cgkings** [comment]
> 

我dd debian11，重装一下，仅安装docker试一下

**Comment by cgkings** [comment]
> @cgkings 服务启动应该没有问题，检查下caddy反代配置是否正确。本地可通过 curl [http://127.0.0.1:{port}/aaa](http://127.0.0.1:%7Bport%7D/aaa) 测试服务是否正常

![image](https://user-images.githubusercontent.com/58586625/148148779-a10eb9cf-4244-4b46-aa46-7fd9eb043e00.png)

**Comment by CareyWang** [comment]
@cgkings 自行修改port到env配置

**Comment by cgkings** [comment]
> @cgkings 自行修改port到env配置

![image](https://user-images.githubusercontent.com/58586625/148149062-add05936-8135-4a9a-b94d-6b6e701b539c.png)

**Comment by cgkings** [comment]
> @cgkings 自己修改port到env配置

![image](https://user-images.githubusercontent.com/58586625/148150877-0cd778e2-9c97-4c29-92cf-e9679a82dee3.png)
我自行安装了caddy2,配置x-go.gq反代本地8002，用x-go.gq可以访问网页，但是获取短链接失败，真是一步一个坎啊

**Comment by cgkings** [comment]
确实太难了，我从网上找了个教程，重装了一下：
1、`wget https://github.com/CareyWang/MyUrls/releases/download/v1.10/linux-amd64.tar.gz`
2、tar解压到/home/myurls，`chmod -R 755 /home/myurls`
3、`cd /home/myurls && ./linux-amd64-myurls.service -domain x-go.gq`
4、编辑 /home/myurls/public/index.html 文件，将 const backend 这里改成自己的域名
5、编辑caddy2配置如下，`systemctl restart caddy`
![image](https://user-images.githubusercontent.com/58586625/148173343-e96f1eb3-8513-4667-9920-93ba069166d0.png)
6、访问x-go--成功，转化短链接--成功，but，访问转换的短链接--失败
![image](https://user-images.githubusercontent.com/58586625/148173571-af196e71-d41b-4a74-8a5e-2276f62602b0.png)
![image](https://user-images.githubusercontent.com/58586625/148173610-4de924b4-a0f1-431f-9212-2c2f228ac8af.png)

**Comment by cgkings** [comment]
ok,搞定了，我步骤没错，就是刚才找的教程没有让安装redis，
sudo apt-get install redis-server -y 
搞定，可以正常转换和访问短链了

**Comment by cs-star** [comment]
https://sub.aa01.ml/   https://zz01.ml/  大佬 对接怎么不能 短链接获取失败不知道哪里设置了
